### ISSUE TITLE
DateTime conversion issues when doing unit test

### ISSUE THREAD

**Issue by eminarcissus** [bitwalker/timex_ecto#56]
The code are as following
Looks like the last digit 05.41213Z and 05.412130Z are not the same when doing ecto conversion(they are compared as String when returned from the view layer

Don't know if this is a bug or is something I'm missing here
Any help would be appreciated :)
```
code: json_response(conn, 200) == render_json(ActivityView, "show.json", activity: gate)
     lhs:  %{"data" => %{"activity_holder" => "ActivityHolder8", "background_img" => nil, "description" => "ActivityDescription8", "end_datetime" => nil, "id" => 54, "is_deleted" => false, "is_stopped" => false, "name" => "Activity8", "wechat_link" => nil, "start_datetime" => "2017-01-13T19:20:05.41213Z"}}
     rhs:  %{"data" => %{"activity_holder" => "ActivityHolder8", "background_img" => nil, "description" => "ActivityDescription8", "end_datetime" => nil, "id" => 54, "is_deleted" => false, "is_stopped" => false, "name" => "Activity8", "wechat_link" => nil, "start_datetime" => "2017-01-13T19:20:05.412130Z"}}
     stacktrace:
       test/controllers/activity_controller_test.exs:46: (test)
```
